### ISSUE TITLE
India update not regular

### ISSUE THREAD

**Issue by arjunaraoc** [osmbe/osm-welcome-belgium#1112]
I think India update is  not happening on a daily basis.  It is showing data with more than 2 days old as of today. Can it be made regular

**Comment by jbelien** [comment]
Hello @arjunaraoc ,
The update is run daily!
But indeed, like it happened today, sometimes the process fails for 1 region and all the regions after are not processed ; that's a known issue and I still need to solve it.

Don't worry though, the auto-update for India should be picked up tomorrow or the day after and if not, I'll run the update manually.

**Comment by arjunaraoc** [comment]
Thanks @jbelien for your response. India update worked today.
