### ISSUE TITLE
Move OSM authentication to OAuth 2.0

### ISSUE THREAD

**Issue by pnorman** [osmbe/osm-welcome-belgium#1196]
OAuth 1.0a is deprecated, and programs which use it to authenticate requests to OpenStreetMap should move to OAuth 2.0. A date has not yet been set for turning off OAuth 1.0a and HTTP Basic.

It's best to move to OAuth 2.0 well in advance of any turn-off, because users may take some time to upgrade software and to re-authenticate.

See https://github.com/openstreetmap/operations/issues/867 for details.

**Comment by jbelien** [comment]
Hello @pnorman ,

Thanks for the notice.
I believe OSM Welcome Tool is already using OAuth 2.0.

![image](https://github.com/osmbe/osm-welcome-tool/assets/1150563/0c85116d-b784-4d1c-bff2-a3b3de8558f8)

Is there something that make you think otherwise ?
If so, I'll be happy to make the necessary changes.

Thanks!

**Comment by danieldegroot2** [comment]
- https://github.com/osmbe/osm-welcome-tool/blob/ec3a3a9802bab7c70f3b3606913b7d003125e06d/config/packages/framework.yaml#L21
- - https://github.com/osmbe/osm-welcome-tool/blob/ec3a3a9802bab7c70f3b3606913b7d003125e06d/config/services.yaml#L9

Note, `api.openstreetmap.org` API url currently can not do OAuth 2 handshake. See https://github.com/openstreetmap/operations/issues/951#issuecomment-1748717154
You can split the `www.` base URL and `api.` API url. See https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

---

Only forks should still have to update to the current (application) version to get these changes.

**Comment by pnorman** [comment]
> I believe OSM Welcome Tool is already using OAuth 2.0

I didn't find it in a quick code search, but if it is, that's good.

**Comment by danieldegroot2** [comment]
@pnorman Yes, it is. Your results may vary depending on what you search.
In this case, it is not using `openstreetmap.org` URL directly. It is using [jbelien/oauth2-openstreetmap](https://github.com/jbelien/oauth2-openstreetmap).

See https://github.com/jbelien/oauth2-openstreetmap/blob/master/src/Provider/OpenStreetMap.php
