### ISSUE TITLE
Newestosm feed change

### ISSUE THREAD

**Issue by sabas** [osmbe/osm-welcome-belgium#12]
I asked Pascal Neis to add the user id to the feed and he did it
https://twitter.com/pascal_n/status/809456541061386240

To get the ID another query isn't needed anymore.

**Comment by joostschouppe** [comment]
Cool! So do we have to adapt the code ASAP or does it keep working for now?

**Comment by sabas** [comment]
No change needed if I understood the current mechanism. But it's useful going ahead (I'm thinking how to refactor the code :-) ).

**Comment by jbelien** [comment]
Sorry it took us almost 3 years! I merge #13 🎉
Thanks a lot for your contribution!
