### ISSUE TITLE
Last Updated Ranges from Current to 7 Days. Many in the 6 and 7 day range

### ISSUE THREAD

**Issue by cliffordsnow** [osmbe/osm-welcome-belgium#1344]
Too many failures to update. Working with data a couple of days old isn't bad but some of these results are troubling.

Last Update:
Africa is current
Asia ranges from 1 day to 6 days ago
Europe ranges from current to 7 days ago
North America  ranges from 1 day to 6 days ago
South America is current

**Comment by cliffordsnow** [comment]
Today I was able to welcome new mappers added over the last few days. 30+. Many require not only feedback but either reverting or repairing their edits. I hope we can get the system fixed so we don't have these backlogs in the future. It looks like someone ran the script today. The first few areas in North America were updated early in the morning and then the rest were updated later. So thanks to who ever ran it again.

**Comment by jbelien** [comment]
Hello @cliffordsnow ,

I've indeed ran the script manually yesterday after adding a few new regions.

I've been pretty busy these last few months and didn't give the care the tool needed but I'll try to keep a closer look on it.

**Comment by cliffordsnow** [comment]
My area is again days behind. I show at least 17 new mappers. I'm happy to help solve this problem unfortunately I'm leaving tomorrow on a 20 day road trip. Trip includes State of the Map US in Salt Lake City UT. The unfortunate part is the lack of time available. Most of the trip just involves driving long distances.

Until we can get a fix, I'm going to put a hold on welcoming new mappers since many of them are getting the welcome late and I believe we do better with timely welcomes.

**Comment by cliffordsnow** [comment]
Wille upgraded OSMCha to  use the OSM OAuth2 authentication. Not sure now this effects the welcome tool.

**Comment by nightpool** [comment]
My area is 3 months behind, is there anything I can do to contribute?

**Comment by jbelien** [comment]
Join discussion on #1413
