### ISSUE TITLE
Tool not working

### ISSUE THREAD

**Issue by AntMadeira** [osmbe/osm-welcome-belgium#1386]
Hi there.

Something is wrong with the tool page.
Here's what I see for June:
![imagem](https://github.com/osmbe/osm-welcome-tool/assets/34066528/53f267a6-5fd9-4226-9f5c-08848995d0cb)

**Comment by bxl-forever** [comment]
Duplicate of issue #1344

**Comment by jbelien** [comment]
As @bxl-forever said, this is a duplicate of #1344 ; join discussion on #1413
