### ISSUE TITLE
Consider adding description how it works

### ISSUE THREAD

**Issue by matkoniecz** [osmbe/osm-welcome-belgium#148]
How it works? Is it for sending fully automatic messages (no human interaction)?

Is it somehow detecting new mappers in a given region?

It would be useful to add some explanation how it works and screenshots.

Is there some public deployment?

Is it possible to check is it used in a given region?

**Comment by jbelien** [comment]
> Is it for sending fully automatic messages (no human interaction)?

No, it detects new mappers in "your" region and suggests a welcome message (based on templates) that you can then (manually) send to the mapper.

> Is it somehow detecting new mappers in a given region?

Yes.

> It would be useful to add some explanation how it works and screenshots.

I can indeed add some explanation on how it works. 😄 
No need for screenshot, the tool is publicly available here: <https://welcome.osm.be/>

> Is there some public deployment?
> Is it possible to check is it used in a given region?

<https://welcome.osm.be/>

**Comment by RicoElectrico** [comment]
The tool pre-fills the OSM message form. It opens in a new window, ready to send.

**Comment by pyrog** [comment]
What happened if there is local areas inside a country ?
Does the user is listed in i.e the country and the area of a local group ?

If somebody send a welcome message from the country, does this is reflected on the local group ?
And vice-versa ?
