### ISSUE TITLE
Contributing guide: clarify what to do with security.xlf and validator.xlf

### ISSUE THREAD

**Issue by RicoElectrico** [osmbe/osm-welcome-belgium#152]
Hi,
The above files are not listed in CONTRIBUTING.MD. From what I gather, these are translation of the Symfony framework? If so, do you just copy them from upstream? 
validator.xlf is actually quite sizable, would be nice if we can save the effort.

**Comment by jbelien** [comment]
Hello @RicoElectrico ,

You're absolutely right, `security.xlf` and `validator.xlf` come from Symfony so you don't have to worry about those if you want to add a new language.

I'll add this information in `CONTRIBUTING.md`.

**Comment by RicoElectrico** [comment]
OK, so I will make a pull request for Polish shortly, because I have translated the core.
