### ISSUE TITLE
bienvenido/welcomed

### ISSUE THREAD

**Issue by mfrasca** [osmbe/osm-welcome-belgium#153]
I'm not a native speaker of neither of the two languages involved in this translation, but translating "not welcomed" to "no bienvenido/a" sounds really weird, as if the person was not welcome (without the 'd').
I would ask a native speaker, but my guess is that "not welcomed (yet)" vs. "welcomed" should be "falta saludar" vs. "se le envió la bienvenida" (literally: "needs to be welcomed" vs. "a welcome message was sent".)

**Comment by jbelien** [comment]
Sounds right. @Zalitoar Could you confirm (and if so submit a fix) ?

I'll also change "Not welcomed" by "Not welcomed yet", sounds indeed less negative.

**Comment by jbelien** [comment]
I realized that I'm already using "Not welcomed yet" everywhere ... except in the chart labels.
I just completely removed "Not welcomed" not for "Not welcomed yet".

Thanks @mfrasca for rising this up! 👍
