### ISSUE TITLE
Message template - iD autofixes

### ISSUE THREAD

**Issue by RicoElectrico** [osmbe/osm-welcome-belgium#157]
This advice:
> A good start is always to check first if there is no error in the area you want to map, so you know if the error is made by you or a previous mapper (documentation). You can enable this feature with I key.

may be harmful - we have had a few mappers who indiscriminately applied fixes suggested by iD, which are not always right. There have been user blocks due to this feature, I think.

**Comment by jbelien** [comment]
Even though I do agree that in some situations, the iD autofix might bring errors, the iD editor is the "official" editor and I think we should trust it.

But if you don't have that confidence in iD for Poland, feel free to not include it in the templates for Poland. Each region can have its own templates with its own recommandations.

**Comment by RicoElectrico** [comment]
I hope that going forward, with our new maintainer responding to OSMF, you'll be right :)

We have had many raised issues being ignored in the past (like `addr:place` support, POI presets that removed `building=yes` etc.

**Comment by joostschouppe** [comment]
iD autofixes are not something I would recommend to a new mapper myself. Unless perhaps like: "hey this is a thing, but read up on the 'why' of the fixes before going crazy. The web editor is proposing an educated openion, not an absolute fact"
For sure, its up to whoever writes a local template, but I wouldn't include this in a default template unless with more context.

**Comment by jbelien** [comment]
>  For sure, its up to whoever writes a local template, but I wouldn't include this in a default template unless with more context.

There is no default template. Each region has full control on its template.

> iD autofixes are not something I would recommend to a new mapper myself.

Do you think we should remove it from our templates for Belgium then ?

**Comment by cliffordsnow** [comment]
Based on my review of new mapper edits, I've given the iD a list of common problems I see. For example buildings not being square. I've asked the developers to provide a warning when they add non squared objects. The are a couple of open issues on this one example. Validator warning are useful but I agree that autofixes, especially with features that the new mapper didn't touch should be ignored. I would not bring up autofixed but instead point them to appropriate learning material, such as learnosm.org.

**Comment by joostschouppe** [comment]
@jbelien : I'll do a proposal for a re-write of our welcome message
