### ISSUE TITLE
Present some statistics

### ISSUE THREAD

**Issue by RicoElectrico** [osmbe/osm-welcome-belgium#160]
I think presenting some stats would make for a great encouragement:
- on the regions card display `X/Y welcomed (Z%)` and highlight it green when it passes an arbitrary threshold like 90%
- make leaderboards for every region

**Comment by jbelien** [comment]
> make leaderboards for every region

What would you like to see in this/those leaderboard(s) ?

**Comment by RicoElectrico** [comment]
I think just a number of mappers welcomed would suffice.
