### ISSUE TITLE
Document how nested regions work

### ISSUE THREAD

**Issue by RicoElectrico** [osmbe/osm-welcome-belgium#168]
I checked and Colombia doesn't list a mapper which was listed in Bogotá. So some de-duplication of mappers does occur, which is great. This should be documented. I guess in the absence of any other hints this is probably done by the order of regions in the config?

**Comment by jbelien** [comment]
Yeah, you're indeed right, at the moment a mapper can be only linked to one single region.

I need to check but I'm pretty sure it can lead to "conflicts".
I noticed [that user](https://welcome.osm.be/tanzania/mapper/14460846) that made a first contribution in Belgium but is now appearing in [Tanzania list of new mappers](https://welcome.osm.be/tanzania/list). I'm guessing this mapper made meanwhile a contribution there but I'll need to check.

**Comment by jbelien** [comment]
Since #808 a new mapper will appear in **every** region it is detected. This should fix the issue with nested regions.
