### ISSUE TITLE
a wiki page

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/osm-welcome-belgium#171]
It was suggested that we create an osm wiki page for this project, so that it can be internationalized more easily. That makes sense, but what would be in there? And how do we reduce duplicate documentation?

I would propose:
- a short intro
- a summary of the contribution guide
- a short user manual

A lot of the content could be copied from https://www.openstreetmap.org/user/LCCWG/diary/398057

**Comment by cliffordsnow** [comment]
I added instructions for using the OSMCha tool. It's currently a markdown document but could be easily converted to a wiki article.

**Comment by matkoniecz** [comment]
> That makes sense, but what would be in there?

Very short description and link to more thorough docs?

**Comment by cliffordsnow** [comment]
I created a Welcome Tool wiki page, https://wiki.openstreetmap.org/wiki/Welcome_tool, using @joostschouppe diary entry. Feel free to edit. As a next step I'd suggest adding in the github section on creating new regions.

**Comment by matkoniecz** [comment]
Note that wiki pages are usually less personal (not in the first person), see https://wiki.openstreetmap.org/wiki/StreetComplete for a comparison

**Comment by joostschouppe** [comment]
I've "factualized" the main text block. Starting to look good. Should we already ask around for translations? Or do we need some more content first?

**Comment by cliffordsnow** [comment]
It feels like there needs more instruction. How can we ask for input from some of the new region people? The Telegram group only has a few of the new regions represented.

**Comment by jbelien** [comment]
> How can we ask for input from some of the new region people? The Telegram group only has a few of the new regions represented.

That's indeed a good point.
Most of the default templates (when there is one) refers to a way to contact the community.
We can probably get those information from there and I would indeed put it in the wiki.
