### ISSUE TITLE
OSM Scotland

### ISSUE THREAD

**Issue by boothym** [osmbe/osm-welcome-belgium#185]
Hi, wondering if someone could create a Scotland region for us? 😃 

name=Scotland
flag=🏴󠁧󠁢󠁳󠁣󠁴󠁿 (this is showing black for me, and no flags are showing for me on the welcome tool - just AT for example)
locales=en (though not sure if "gd" for Scots Gaelic should also be included?)

The OSM relation would be: https://www.openstreetmap.org/relation/58446

Thanks!

**Comment by jbelien** [comment]
No worries, I'll take care of it in the next few days.

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/scotland/list

**Comment by jbelien** [comment]
I have the same black flag on Windows but the correct flag on Firefox on Android so I guess it will depend on your browser and OS.

**Comment by boothym** [comment]
Thanks! 😄
