### ISSUE TITLE
Austria is not in Poland

### ISSUE THREAD

**Issue by matkoniecz** [osmbe/osm-welcome-belgium#190]
https://welcome.osm.be/poland/mapper/14063456

https://www.openstreetmap.org/changeset/114098603 is not in Poland

this sole changeset listed as reason for classifying as Polish mapper is not in Poland

![screen](https://user-images.githubusercontent.com/899988/143619562-78fa1ef5-1d6f-413a-b214-f5dbd9a99049.png)
![screen01](https://user-images.githubusercontent.com/899988/143619565-d3f88791-8c58-46a6-ab32-744f1181c200.png)

**Comment by jbelien** [comment]
Since #808 a new mapper will appear in **every** region it is detected. This should fix the issue.
