### ISSUE TITLE
Show status in region list

### ISSUE THREAD

**Issue by cliffordsnow** [osmbe/osm-welcome-belgium#194]
The list page shows the regions. I'd like to see a indicator if the recent additions have been notified. The images are just a possibility. 

The calculation to determine if the recent additions are complete would be to check if the additions have been welcomed or if their is a note. (I get an occasional SEO user that changes the user name to match their customer. They never reply to welcome messages or changeset comments. I have given up sending them welcome messages.) 

![welcome_tool_complete](https://user-images.githubusercontent.com/3290977/143783875-91d3b9c3-3d50-4cd5-87a4-7fd64506d835.png)
![welcome_tool_complete2](https://user-images.githubusercontent.com/3290977/143783876-4a4d4373-2752-4aff-a525-d777ed2edc2d.png)

**Comment by jbelien** [comment]
Related to #160

**Comment by jbelien** [comment]
I've added a progress bar.
A mapper is considered as "checked" if he/she has been welcomed or if a not has been added to that mapper.

![image](https://user-images.githubusercontent.com/1150563/147766813-2739684c-1696-4b38-b218-385e2d524573.png)
