### ISSUE TITLE
This is a parallel repo of the repo at Framagit

### ISSUE THREAD

**Issue by M1dgard** [osmbe/osm-welcome-belgium#2]
Also see the [issues](https://framagit.org/Midgard/osm-welcome-belgium/issues) at the [original repo](https://framagit.org/Midgard/osm-welcome-belgium) over at [Framagit](https://framagit.org) (Framasoft's GitLab instance).

**Comment by Zverik** [comment]
Does it mean I shouldn't make pull requests here?

**Comment by M1dgard** [comment]
@Zverik It was possible to make PRs here at GitHub or at Framagit. This meant that unfortunately, discussion could be split up. Now I've moved everything over to here.

I hadn't really thought that this tool would be useful to anybody else when creating the repo. It was cloned to the osmbe organization at GitHub (not by me) leaving us with the two separate repos.
