### ISSUE TITLE
Improve presentation of countries in main page

### ISSUE THREAD

**Issue by sabas** [osmbe/osm-welcome-belgium#20]
https://github.com/osmbe/osm-welcome-belgium/blob/2.x/templates/app/home/index.html.twig

**Comment by jbelien** [comment]
Most definitely! 👍

**Comment by jbelien** [comment]
![image](https://user-images.githubusercontent.com/1150563/129919551-3e832c33-7e46-4b26-90a3-2a295e7d9c88.png)

**Comment by jbelien** [comment]
@sabas Any suggestion or is the current version "good enough" ? 😄

**Comment by sabas** [comment]
Perfect!
