### ISSUE TITLE
Login flow

### ISSUE THREAD

**Issue by sabas** [osmbe/osm-welcome-belgium#21]
https://github.com/sabas/oauth1-openstreetmap

**Comment by jbelien** [comment]
I think they switched to OAuth 2 meanwhile !

**Comment by jbelien** [comment]
See https://github.com/osmItalia/welcome-tool/blob/master/index.php#L41 (thanks @sabas)

**Comment by jbelien** [comment]
- https://github.com/knpuniversity/oauth2-client-bundle
- https://github.com/jbelien/oauth2-openstreetmap

**Comment by jbelien** [comment]
Working locally but not on https://osm-welcome-tool.herokuapp.com/
Related to https://github.com/knpuniversity/oauth2-client-bundle/issues/315 ?

**Comment by jbelien** [comment]
✔️  Fixed: https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly
