### ISSUE TITLE
Add note should assign to current logged in user

### ISSUE THREAD

**Issue by sabas** [osmbe/osm-welcome-belgium#22]
![image](https://user-images.githubusercontent.com/1304918/128671047-7e4db199-55b6-4acd-a62d-8a92d48d8adf.png)

https://github.com/osmbe/osm-welcome-belgium/blob/2.x/src/Controller/App/MapperController.php#L34

**Comment by jbelien** [comment]
Indeed, you're absolutely right.
It's setup like this for now because the authentication flow is not ready yet.
