### ISSUE TITLE
Changesets dropdown

### ISSUE THREAD

**Issue by sabas** [osmbe/osm-welcome-belgium#23]
This doesn't work at the moment

![image](https://user-images.githubusercontent.com/1304918/128671321-0bad5fe7-452f-48a6-a555-5e86ae918033.png)

**Comment by jbelien** [comment]
Yeah, I spent a few hours on it already but didn't succeed to make it work ... yet 😄 

I tried with Vue.js and AlpineJS + PopperJS.
