### ISSUE TITLE
Add a flag in the user list for the welcome state

### ISSUE THREAD

**Issue by LorenzoStucchi** [osmbe/osm-welcome-belgium#24]
Could be useful to have a column on the user list page ([example](https://osm-welcome-tool.herokuapp.com/italy/list/2021/8)) with a flag for the user that already receive the welcome message

**Comment by jbelien** [comment]
Excellent idea!
It's indeed planned 👍

**Comment by jbelien** [comment]
Column "Welcomed" added in the list.

![image](https://user-images.githubusercontent.com/1150563/129483596-1b1fccdd-cd4e-4c9f-ac80-f7f9f43e26a3.png)
