### ISSUE TITLE
Issue with Germany

### ISSUE THREAD

**Issue by jbelien** [osmbe/osm-welcome-belgium#262]
There is something wrong with the detection of new mappers in Germany.

I though it was the size of the country but China was just added and it works just fine.

@willemarcel Any idea why https://osmcha.org/api/v1/aoi/5489911b-e978-4983-bd71-8055654339df/changesets/?page_size=500 generates an error 500 ?

Thanks.

**Comment by willemarcel** [comment]
@jbelien It seems something wrong with the Germany borders geometry. I could run [another query](https://osmcha.org/?filters=%7B%22geometry%22%3A%5B%7B%22label%22%3A%7B%22coordinates%22%3A%5B%5B%5B6.399037%2C49.525998%5D%2C%5B6.124432%2C50.175206%5D%2C%5B6.368525%2C50.370215%5D%2C%5B6.032897%2C50.777139%5D%2C%5B5.910851%2C51.142283%5D%2C%5B6.215967%2C51.276087%5D%2C%5B5.910851%2C51.90165%5D%2C%5B6.978757%2C52.257922%5D%2C%5B6.765176%2C52.574285%5D%2C%5B7.100803%2C52.777783%5D%2C%5B7.157471%2C53.228938%5D%2C%5B6.76082%2C53.755347%5D%2C%5B8.645854%2C54.927306%5D%2C%5B10.358583%2C54.761314%5D%2C%5B11.920994%2C54.475235%5D%2C%5B14.261158%2C54.77955%5D%2C%5B14.261158%2C53.909729%5D%2C%5B14.447693%2C53.224933%5D%2C%5B14.159412%2C52.827166%5D%2C%5B14.651185%2C52.570255%5D%2C%5B14.546541%2C52.397536%5D%2C%5B14.766991%2C52.210893%5D%2C%5B14.631329%2C51.761832%5D%2C%5B14.953526%2C51.42472%5D%2C%5B15.07223%2C51.255225%5D%2C%5B14.765754%2C50.815685%5D%2C%5B14.613135%2C50.90132%5D%2C%5B14.562261%2C51.008142%5D%2C%5B14.392684%2C51.050803%5D%2C%5B14.477473%2C50.858522%5D%2C%5B12.223012%2C50.125336%5D%2C%5B12.569024%2C49.915035%5D%2C%5B12.410045%2C49.746131%5D%2C%5B12.690991%2C49.417949%5D%2C%5B13.065057%2C49.296127%5D%2C%5B13.878653%2C48.77501%5D%2C%5B13.785136%2C48.552654%5D%2C%5B13.710323%2C48.5155%5D%2C%5B13.541993%2C48.583596%5D%2C%5B13.448476%2C48.366608%5D%2C%5B12.773148%2C48.114806%5D%2C%5B13.06305%2C47.839355%5D%2C%5B12.932127%2C47.726247%5D%2C%5B13.091105%2C47.713664%5D%2C%5B13.044347%2C47.455047%5D%2C%5B12.819907%2C47.581361%5D%2C%5B12.773148%2C47.6696%5D%2C%5B12.642225%2C47.663303%5D%2C%5B12.576763%2C47.600282%5D%2C%5B12.240103%2C47.688489%5D%2C%5B12.286861%2C47.562434%5D%2C%5B11.145958%2C47.328429%5D%2C%5B10.809298%2C47.492974%5D%2C%5B10.472637%2C47.530872%5D%2C%5B10.463286%2C47.32209%5D%2C%5B10.154681%2C47.214213%5D%2C%5B9.920889%2C47.511926%5D%2C%5B9.500064%2C47.50561%5D%2C%5B8.770634%2C47.682194%5D%2C%5B8.30305%2C47.486654%5D%2C%5B7.592323%2C47.530872%5D%2C%5B7.51751%2C47.688489%5D%2C%5B7.631822%2C48.310815%5D%2C%5B7.912372%2C48.69498%5D%2C%5B8.192922%2C48.965848%5D%2C%5B7.332568%2C49.131338%5D%2C%5B6.72471%2C49.125218%5D%2C%5B6.399037%2C49.525998%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%2C%22value%22%3A%7B%22coordinates%22%3A%5B%5B%5B6.399037%2C49.525998%5D%2C%5B6.124432%2C50.175206%5D%2C%5B6.368525%2C50.370215%5D%2C%5B6.032897%2C50.777139%5D%2C%5B5.910851%2C51.142283%5D%2C%5B6.215967%2C51.276087%5D%2C%5B5.910851%2C51.90165%5D%2C%5B6.978757%2C52.257922%5D%2C%5B6.765176%2C52.574285%5D%2C%5B7.100803%2C52.777783%5D%2C%5B7.157471%2C53.228938%5D%2C%5B6.76082%2C53.755347%5D%2C%5B8.645854%2C54.927306%5D%2C%5B10.358583%2C54.761314%5D%2C%5B11.920994%2C54.475235%5D%2C%5B14.261158%2C54.77955%5D%2C%5B14.261158%2C53.909729%5D%2C%5B14.447693%2C53.224933%5D%2C%5B14.159412%2C52.827166%5D%2C%5B14.651185%2C52.570255%5D%2C%5B14.546541%2C52.397536%5D%2C%5B14.766991%2C52.210893%5D%2C%5B14.631329%2C51.761832%5D%2C%5B14.953526%2C51.42472%5D%2C%5B15.07223%2C51.255225%5D%2C%5B14.765754%2C50.815685%5D%2C%5B14.613135%2C50.90132%5D%2C%5B14.562261%2C51.008142%5D%2C%5B14.392684%2C51.050803%5D%2C%5B14.477473%2C50.858522%5D%2C%5B12.223012%2C50.125336%5D%2C%5B12.569024%2C49.915035%5D%2C%5B12.410045%2C49.746131%5D%2C%5B12.690991%2C49.417949%5D%2C%5B13.065057%2C49.296127%5D%2C%5B13.878653%2C48.77501%5D%2C%5B13.785136%2C48.552654%5D%2C%5B13.710323%2C48.5155%5D%2C%5B13.541993%2C48.583596%5D%2C%5B13.448476%2C48.366608%5D%2C%5B12.773148%2C48.114806%5D%2C%5B13.06305%2C47.839355%5D%2C%5B12.932127%2C47.726247%5D%2C%5B13.091105%2C47.713664%5D%2C%5B13.044347%2C47.455047%5D%2C%5B12.819907%2C47.581361%5D%2C%5B12.773148%2C47.6696%5D%2C%5B12.642225%2C47.663303%5D%2C%5B12.576763%2C47.600282%5D%2C%5B12.240103%2C47.688489%5D%2C%5B12.286861%2C47.562434%5D%2C%5B11.145958%2C47.328429%5D%2C%5B10.809298%2C47.492974%5D%2C%5B10.472637%2C47.530872%5D%2C%5B10.463286%2C47.32209%5D%2C%5B10.154681%2C47.214213%5D%2C%5B9.920889%2C47.511926%5D%2C%5B9.500064%2C47.50561%5D%2C%5B8.770634%2C47.682194%5D%2C%5B8.30305%2C47.486654%5D%2C%5B7.592323%2C47.530872%5D%2C%5B7.51751%2C47.688489%5D%2C%5B7.631822%2C48.310815%5D%2C%5B7.912372%2C48.69498%5D%2C%5B8.192922%2C48.965848%5D%2C%5B7.332568%2C49.131338%5D%2C%5B6.72471%2C49.125218%5D%2C%5B6.399037%2C49.525998%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%7D%5D%7D) with a manually draw border.

**Comment by jbelien** [comment]
Okay, nice, thanks @willemarcel !

I'll check (and update) the GeoJSON used by the query for Germany.

**Comment by GITMichaelK** [comment]
Thank you @jbelien,
I've used [this page](https://peteris.rocks/blog/openstreetmap-administrative-boundaries-in-geojson/) and went from there to [this one](http://polygons.openstreetmap.fr/?id=51477) using the ID51477 from [OSM](https://www.openstreetmap.org/relation/51477). I'll be happy to learn, what I've done wrong.

**Comment by jbelien** [comment]
> I've used [this page](https://peteris.rocks/blog/openstreetmap-administrative-boundaries-in-geojson/) and went from there to [this one](http://polygons.openstreetmap.fr/?id=51477) using the ID51477 from [OSM](https://www.openstreetmap.org/relation/51477). I'll be happy to learn, what I've done wrong.

That was the correct procedure. 👍 
You (probably) took the most detailed geometry and the resulting GeoJSON file was quite big (3.5MB).
I've updated it with a simplified geometry (1198 nodes instead of 154383) and everything works just fine now. 🥳 

https://welcome.osm.be/germany/list

**Comment by GITMichaelK** [comment]
Thanks a lot @jbelien for that solution!  
I added now a proposal for the [German Welcome-text](https://github.com/osmbe/osm-welcome-tool/pull/273); also I've seen your approach with the [Wiki](https://github.com/osmbe/osm-welcome-tool/issues/171); please let me now, if I could help. Or you comment my proposal in the actual pull request.  
Regards and greetings form Germany
Michael
