### ISSUE TITLE
Month in URL can out of range when use `<` and `>` button

### ISSUE THREAD

**Issue by LaoshuBaby** [osmbe/osm-welcome-belgium#263]
Now we are at this page, and can use those 2 button to switch to privious/next month

![图片](https://user-images.githubusercontent.com/42690037/145576699-e4c0a65e-9f78-4ba2-94d5-319a67e22500.png)

today is 2021/12/10, and when I use `>` , the url bump to 2021/13

![图片](https://user-images.githubusercontent.com/42690037/145576814-545dee76-984f-411d-a48e-69649e7f9ac5.png)

But there can't be 13 months in a year

-----

Now I click it, the text think I'm in Jan 2022, but the url is 2021/13

![图片](https://user-images.githubusercontent.com/42690037/145576987-33764b8d-8ebf-483f-8c44-1e45168b11b5.png)

Now the `<` button direct to 2022/0 and `>` direct to 2022/2

-----

If I click the `<` , it will see 2022/0 as Dec 2021

![图片](https://user-images.githubusercontent.com/42690037/145577198-43dd7f6c-395f-40ee-ac05-056143180760.png)

**Comment by jbelien** [comment]
There is indeed a logic that makes `2021/13` or `2022/0` work but you have a fair point.
It's not really user friendly to have those `2021/13` in the URL, it should indeed be redirected to `2022/01`.

**Comment by jbelien** [comment]
I noticed that `2021/13` is "redirected" to `2021/01` instead of `2022/01`.
I'll fix it too!
