### ISSUE TITLE
LogIN / LogOut issue

### ISSUE THREAD

**Issue by GITMichaelK** [osmbe/osm-welcome-belgium#275]
I'm starting my browser from scratch, the cache is clear. Then I called the [Blog-page](https://www.openstreetmap.org/user/LCCWG/diary/398057) and from there "[Try it out](https://welcome.osm.be/)"; the LogIn-Button now is active.  
I clicked it, entered Username and password and ENTER; this leads to [this page](https://welcome.osm.be/favicon.ico/list) showing
> Oops! An Error Occurred
> The server returned a "500 Internal Server Error".
> Something is broken. Please let us know ...

Going back to the [former page](https://welcome.osm.be/), the LogIn-Button has changed to **LogOut**, so I'm still loggged-IN.
Clicking LogOut, this leads to [this page](https://welcome.osm.be/logout/list) showing
> Oops! An Error Occurred
> The server returned a "500 Internal Server Error".
> Something is broken. Please let us know ...

**Comment by jbelien** [comment]
Thanks for the report.

Could you test it in private/incognito mode of your browser to see if the issue happens there too ?

**Comment by Jakkajakka** [comment]
Same here logout error
windows 10 firefox

**Comment by jbelien** [comment]
I'll have a look ASAP!

**Comment by jbelien** [comment]
Okay, I've found where the issue comes from!
`/login` and `/logout` are redirected to `/login/list` and `/logout/list` since 6fbcbc62c476e43cce6e39042704e7a1a6f32878

I'll fix it (hopefully) tomorrow morning!

**Comment by GITMichaelK** [comment]
> Could you test it in private/incognito mode
Done and yes, it behaves the same way.  
Firefox 95.0 on Manjaro Linux, KDE Plasma Version: 5.23.4

**Comment by jbelien** [comment]
Fixed (bf7ca72667ebc0544e8d9fcd101c0108c0f6b07d + 2dda2b655f1c3f7549aedac5a2e28b120a58456c)
