### ISSUE TITLE
Highlight also experienced mappers new to the area

### ISSUE THREAD

**Issue by mfrasca** [osmbe/osm-welcome-belgium#279]
as I understood the rationale behind this tool, it helps us welcome newbies to OSM, region-wise.  in OSM we also have, how to say it, "newbies regions"?

at least in Latin America and in Africa there's regions where the bulk of contributions come from experienced mappers travelling through the region, virtually or physically.  the tool as it stands now will not alert the small local communities of this valuable temporary presence.

sometimes experienced mappers come visit one's region of interest without first checking with the local community, tagging according to a different logic than the one accepted in the region.  this would be a threat, and if it's experienced mappers posing it, the tool will also not warn us.

I wish the tool would also highlight contributions from experienced mappers new to the area (new as far as the tool is concerned).

**Comment by jbelien** [comment]
The Welcome Tool only detects new mappers (less that 50 changesets) and the first(s) changeset(s) of those mappers, so there shouldn't be any "experienced mapper" detected by the Welcome Tool (unless those "experienced mapper" created a new account).

Do you have an example of one of those "experienced mapper" that has been detected by the Welcome Tool ?

**Comment by jbelien** [comment]
Oh sorry, I understood the question wrong ...
You want to detect "experienced mappers" **AND** new mappers.

That might be tricky to implement and will drastically increase the detection work.
What would you consider as "experienced mapper" ?

**Comment by mfrasca** [comment]
> That […] will drastically increase the detection work.

possibly, but I guess not in "newbies areas".  I'm making up the term to express the concept of an area which is a newbie itself.  the areas I'm considering have typically 0-5 editors per day, or a hard kern of 1-2 mappers active almost constantly, and occasionally external individuals or groups swiping over the area.  

Belize (last 31 days 50th percentile = 1 editor):
![image](https://user-images.githubusercontent.com/122869/146678284-033ef279-2a3c-4a99-ae46-1f6cef2b6690.png)
Panama (last 31 days 50th percentile = 2 editors):
![image](https://user-images.githubusercontent.com/122869/146678306-59a4e518-0ba8-462a-b457-49a709518b5e.png)
Morocco (last 31 days 50th percentile = 7 editors):
![image](https://user-images.githubusercontent.com/122869/146678380-4e2510e0-e4ab-4f2e-8d1c-686553a5a8b4.png)
Sierra Leone (last 31 days 50th percentile = 3 editors):
![image](https://user-images.githubusercontent.com/122869/146678417-07223ba3-d3f4-4a9f-a812-84a59bc406c5.png)
Liberia (last 31 days 50th percentile = 1 editor):
![image](https://user-images.githubusercontent.com/122869/146679735-ff47edcf-7360-4cc2-b2e2-036e5d8fc1e8.png)


> What would you consider as "experienced mapper" ?

oh, actually I used the expression to mean anything filtered out by the tool, so more than 50 edits.  but indeed it would be useful to have an extra (positive) alert for some higher profile person coming by, or a (neutral) alert for people belonging to organized mapping, or a (red) alert for mappers who's had 2 or more locks by the DWG.

I was just thinking of optionally turning off the 50 edits filter.

the occasion to do open this issue was [a recent 300 edits French mapper visiting Kuna Yala](https://www.openstreetmap.org/user/No%C3%A9%20G/history#map=8/8.665/-79.887).

**Comment by joostschouppe** [comment]
I think this outside of scope for the welcome tool. It's a really interesting thing to do, but it's more a "monitoring tool" than a "welcome tool". I think it would be best to start playing with OsmCHA to see if you can find a decent filter to detect this kind of thing (rather hard I think!) or your own detection flow (for example, process the country data weekly to extract "known users", and compare that to a list of all recent mappers in the country). Only after that has proven to work, and is being copied elsewhere, would it make sense to build a globally scalable tool around it.

**Comment by mfrasca** [comment]
I understand the point of view "outside scope", yet I think it would be valuable to have here, because this welcome tool is a very user friendly thing, and it could be the one-stop solution for administration of what I above called newbie-areas.  I don't know if I have the energy to experiment with the filter @joostschouppe suggests.  it would be better to work at it in (small) team, but in the community where I landed there isn't really anybody else but me.
