### ISSUE TITLE
Error in the link to the translation

### ISSUE THREAD

**Issue by LorenzoStucchi** [osmbe/osm-welcome-belgium#28]
The text "notes" is translated into the translation file but it is not correctly linked with the translation and this produces the missing translation.

https://github.com/osmbe/osm-welcome-belgium/blob/31ed98faf19923929636a4ea0fcad2b929427dc6/translations/messages%2Bintl-icu.it.xlf#L140

<img width="858" alt="Schermata 2021-08-23 alle 12 38 43" src="https://user-images.githubusercontent.com/29042221/130434268-9a76452b-8b42-48a8-9fa1-27dd187fd44a.png">

**Comment by jbelien** [comment]
Grazie @LorenzoStucchi !

I've added the missing translation.

https://github.com/osmbe/osm-welcome-belgium/blob/db850ba21b56a735bf777aa76398eef867737377/translations/messages%2Bintl-icu.it.xlf#L200-L203

Could you update the file with the correct translation in Italian ?

**Comment by LorenzoStucchi** [comment]
I update the file into the PR https://github.com/osmbe/osm-welcome-belgium/pull/29

Thanks :)
