### ISSUE TITLE
Allow for custom regions

### ISSUE THREAD

**Issue by tordans** [osmbe/osm-welcome-belgium#281]
I would like to use a list of custom regions, not just a whole country.

For example:
- Berlin Neukölln, which is the area a very local community monitors and keeps up to data
- Berlin-Brandenburg, which is the area of our [local Stammtisch](https://wiki.openstreetmap.org/wiki/Berlin/Stammtisch)
- The area of the project https://www.zesplus.de/forschungsprojekt, which is <details><summary>this area…</summary><pre>area["boundary"="administrative"]["admin_level"="8"]["name"="Zeuthen"];
area["boundary"="administrative"]["admin_level"="8"]["name"="Eichwalde"];
area["boundary"="administrative"]["admin_level"="8"]["name"="Schulzendorf"];
area["boundary"="administrative"]["admin_level"="8"]["name"="Wildau"];
area["boundary"="administrative"]["admin_level"="8"]["name"="Königs Wusterhausen"];
area["boundary"="administrative"]["admin_level"="8"]["name"="Schönefeld"];
</pre></details>
- The area of https://www.openstreetmap.org/relation/1427697 which is where a similar project to ZES+ will take place next year

Is something like this possible already or planned?

**Comment by jbelien** [comment]
You can have anything you like as a region, you just need to provide the related geometry in a GeoJSON file!

So it's already possible.

**Comment by tordans** [comment]
Thanks @jbelien. And I just found https://github.com/osmbe/osm-welcome-tool/blob/2.x/CONTRIBUTING.md#add-a-new-region, so I will follow that. Thanks!
