### ISSUE TITLE
Wants Review

### ISSUE THREAD

**Issue by cliffordsnow** [osmbe/osm-welcome-belgium#30]
One enhancement I'd like to recommend is to grab wants review from OSMCha. We could start just by looking at the first edit. Not sure if the welcome tool can grab the results from OSMCha otherwise a checkbox would need to be added just like the existing  welcomed and replied one.

**Comment by jbelien** [comment]
The "Review requested" tag (and all other tags from OSMCha) is already displayed.
![image](https://user-images.githubusercontent.com/1150563/131997005-64f798af-165b-4f41-a021-49974fb1a87d.png)

If the changeset has been checkd in OSMCha, it is also already displayed.
![image](https://user-images.githubusercontent.com/1150563/131997357-a1f531dd-9359-4f83-89eb-c540918d7c33.png)

I try to keep the Welcome Tool as simple as possible and not duplicate features that are already available in OSMCha (for instance).
You can easily open a changeset in OSMCha from the Welcome Tool and check the changeset there.
Check tag will be automatically been displayed in the Welcome Tool at the next run (or when you'll run the tool manually - when that feature is added, see #18)

Does that answer to your request or am I missing something ?

**Comment by cliffordsnow** [comment]
For the initial tool, I agree just having it displayed with the changeset is sufficient. At some point in a future release, I'd like to see something on the list page highlighting mappers requesting a changeset review. For example, I just had https://www.openstreetmap.org/changeset/110465636 where a new mapper was trying to solve a very complex problem, on their first edit! Reviewing new mappers who request a review ranks higher on my priority list than others.

**Comment by joostschouppe** [comment]
I think we should probably ask people who use the tool to use osmcha to validate/invalidate the changesets. That way, others know of the user has been welcomed as well as checked. However, I'm a bit confused. I marked this changeset as "good" https://osmcha.org/changesets/113363045/ , but it doesn't show up in https://welcome.osm.be/belgium/mapper/14403247 . You mention the "checked" status will show up in the tool, but I don't see any flag in osmcha to add this...

**Comment by jbelien** [comment]
> I marked this changeset as "good" https://osmcha.org/changesets/113363045/ , but it doesn't show up in https://welcome.osm.be/belgium/mapper/14403247 . 

When did you do that ?
I'm only refreshing the data once a day.

> You mention the "checked" status will show up in the tool, but I don't see any flag in osmcha to add this...

All the tags I'm displaying in the tool come from OSMCha.
I'm assuming that the "checked" tag comes from the "Verify > Good" button in OSMCha.

**Comment by joostschouppe** [comment]
Hmmm, if it is only updated daily, maybe it does make sense to add an explicit flag "user's changeset was reviewed" next to the "user was welcomed" flag.

**Comment by cliffordsnow** [comment]
As far as I know, it only shows in OSMCha. It should leave a changeset comment on the review, good or bad, but only if the reviewer remembers to post the note.
