### ISSUE TITLE
Contributing documentation

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/osm-welcome-belgium#33]
I'm willing to help write Contributor help documentation, if you just post the places where the docs are for:
How to add a country?
How to add a language?
How to add a localized welcome message?

Note to self: include something about The message subject should probably be more "personal"; especially since people will be getting quite a few messages from osm.org at the start

**Comment by jbelien** [comment]
I didn't write any documentation yet but it's indeed on my to-do list.
Any help is welcome, I'll keep you updated!

**Comment by jbelien** [comment]
See [CONTRIBUTING.md](https://github.com/osmbe/osm-welcome-tool/blob/2.x/CONTRIBUTING.md)

Feel free to reopen the issue if I forgot something.
