### ISSUE TITLE
Missing two new mappers

### ISSUE THREAD

**Issue by cliffordsnow** [osmbe/osm-welcome-belgium#399]
The welcome tool didn't pick up two new mappers. Details below. One used StreetComplete the other use something called FireYak. Neither of which should make a difference. Both made edits in Washington State.

http://osmcha.org/changesets/117495458  http://osm.org/user/CullenW
        Add maximum heights
        State Route 26 West, Grant County, Washington, United States of America
----
http://osmcha.org/changesets/117493837  http://osm.org/user/Tweaver
        updated fire hydrant details with FireYak v1.3.9 (124)
        Viking Road, Cowlitz County, Washington, United States of America

**Comment by jbelien** [comment]
Hello @cliffordsnow ,

I fully rely on OSMCha API for mappers detection.
I'll need to investigate why those 2 mappers were not picked up by OSMCha.

**Comment by jbelien** [comment]
This issue is now most likely fixed (see #801) !
There was an issue with the daily update if one of the new mapper detected by OSMCha deleted his/her account meanwhile.
There was another issue if there were too many new mappers ; the request to get their details was truncated.
