### ISSUE TITLE
Session time too short

### ISSUE THREAD

**Issue by RicoElectrico** [osmbe/osm-welcome-belgium#400]
Hi,
It seems that (I don't know Symfony) the session time is default 30 minutes. A longer value like 7 days would be more reasonable to me.

**Comment by jbelien** [comment]
To be honest I don't see the point of extending the "length" of the session.
If the session is expired, you just have to log in again (see #401)

**Comment by angoca** [comment]
What is the purpose to login again? This web application is not providing sensitive information, like a bank.
Instead, I see this like the main OpenStreetMap page, where you log in once, and if you haven't used it for weeks, it logouts.

I have some issues with this logout feature. In fact, I open several users at the same time (different tabs) and I analyze each of them. Sometimes, it took a while to analyze some of them, and when I go back to the last one, the session has been invalidated, and I cannot click on "X has been welcomed", so I have to go back to main screen, login, go to my area, and search the user again.

**Comment by jbelien** [comment]
Okay, I get your point.
I'll extend the session lifetime.
