### ISSUE TITLE
Move new mappers to correct region

### ISSUE THREAD

**Issue by cliffordsnow** [osmbe/osm-welcome-belgium#403]
Occasionally I get a new mapper on my list that belongs to an adjacent region. Would be nice to be able to move them to the correct list.

**Comment by jbelien** [comment]
Seems like a good idea indeed! 👍 

If the "correct" region is not available in the tool, I suggest then to unassign the user to a region.

**Comment by jbelien** [comment]
Since #808 a new mapper will appear in **every** region it is detected.
