### ISSUE TITLE
Change month easily

### ISSUE THREAD

**Issue by angoca** [osmbe/osm-welcome-belgium#443]
I like to go back to previous months, to see the current quantity of changesets and identify the biggest ones. I like to establish contact with the engaged ones and to see if they haven't replied. However, changing months is not easy, I have to do many clicks.

It will be fun to have a list of recent months to click directly.

**Comment by jbelien** [comment]
The main goal of the tool is to welcome new mappers. It doesn't really makes sense to welcome mappers many months after their first contribution.

So even though I understand your request I don't really think it's in the scope of the project.

If you really need to go back to a specific month, you can update the URL: `https://welcome.osm.be/REGION/list/YYYY/MM` where `YYYY` is the year and `MM` the month.
