### ISSUE TITLE
recognize deleted status of OSM accounts

### ISSUE THREAD

**Issue by mfrasca** [osmbe/osm-welcome-belgium#493]
https://welcome.osm.be/panama/mapper/14875828
if you check their changesets on OSM, the user is not named, but reported as "deleted".
would it be possible for the welcome tool to add an "account deleted" event in the user timeline?

**Comment by jbelien** [comment]
Excellent idea! 👍

**Comment by datendelphin** [comment]
Please consume https://planet.openstreetmap.org/users_deleted/ for GDPR complience
Related: because the website does not mention any one or any organisation for being responsible for it, people come complain to the OSMF. Please add that information, who is responsible for that website.

**Comment by jbelien** [comment]
> Please consume https://planet.openstreetmap.org/users_deleted/ for GDPR complience

Thanks! I'll try to find a moment to implement that cleaning procedure.

---

> Related: because the website does not mention any one or any organisation for being responsible for it, people come complain to the OSMF. Please add that information, who is responsible for that website.

I think it's clearly mentioned on the homepage:
> Developed by [OpenStreetMap Belgium](https://openstreetmap.be/) and supported by the [Local Chapters and Communities Working Group](https://wiki.osmfoundation.org/wiki/Local_Chapters_and_Communities_Working_Group).

I can't really say more than that.

**Comment by datendelphin** [comment]
Yes that's good. Didn't look there
