### ISSUE TITLE
Address the False Positives issue.

### ISSUE THREAD

**Issue by mfrasca** [osmbe/osm-welcome-belgium#494]
in the country I'm following, we have very few new mappers, so few that our statistics are overly impacted by non real matches:

there's people, in particular beginners, who would submit world-spanning changesets, containing possibly just two edits, like one in New Zealand, and one in Alaska (or one in California, and one in South America ---- much more common).

it would be nice if we could tag the event as irrelevant, so that it will be filtered out in the overview: there's no need to welcome them, and there's no need for them to reply.

**Comment by jbelien** [comment]
In most regions, they use the note for such use case (SEO spam, ...).

**Comment by mfrasca** [comment]
well, yes, sure, I can write a note, but it will still be in the way, distract the reader, alter statistics.

**Comment by mfrasca** [comment]
for July 2022 we have 4 such false positives in Panama, out of 9 matches. I welcomed 2 people, and I wish to make clear that it's still 3 to consider, not 7.

**Comment by jbelien** [comment]
Since #808 a new mapper will appear in **every** region it is detected. This should fix the issue.
