### ISSUE TITLE
why doesn't this user show as new editor?

### ISSUE THREAD

**Issue by mfrasca** [osmbe/osm-welcome-belgium#495]
[PeteZivkov](https://www.openstreetmap.org/user/PeteZivkov/history) is a new user, they edited in what is possibly their base town, and in Panama, and it's not mentioned as new editor for Panama.  first two changesets in California, third in Panama. All their first 5 changesets were on same day 30th of March. I don't know what might have confused the logic for identifying new editors:

| Palo Alto | Panama |
| ---- | ---- |
|1, 2 | |
| | 3 |
| 4 | |
| | 5, 6, 7 |
| 8, 9| |
| | 10, 11|
|12, 13, 14, 15 ||

**Comment by jbelien** [comment]
A new mapper can only be "connected" to one single region at the moment.
I indeed need to investigate how it happens if a new mapper is related to several region (see #399).

**Comment by jbelien** [comment]
This issue is now most likely fixed (see #801) !
There was an issue with the daily update if one of the new mapper detected by OSMCha deleted his/her account meanwhile.
There was another issue if there were too many new mappers ; the request to get their details was truncated.
