### ISSUE TITLE
[question] who welcomes who?

### ISSUE THREAD

**Issue by govvin** [osmbe/osm-welcome-belgium#547]
Is there a way to find out who welcomed who? 

Or stats about who enabled the "has been welcomed" or "has replied" check boxes?

**Comment by jbelien** [comment]
You can find all that on a profile in the "Timeline" card.

![image](https://user-images.githubusercontent.com/1150563/168429455-aef967b9-d116-4fd6-af46-e4fc00b37ef5.png)

**Comment by govvin** [comment]
Oh, yes. I've seen that.

I was hoping like there's a summary of that for the month, like when you view the list of new mappers by the month.

**Comment by jbelien** [comment]
That could indeed be added in the future.
