### ISSUE TITLE
welcome graph slowing down

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/osm-welcome-belgium#622]
The graph that shows the progress per country is becoming very long. On some devices, apparently this means you have to wait a few moments for it to load until you can do anything else. Also it's not very readible anymore if it's so long. SO perhaps better to imit to, say, three months?

**Comment by jbelien** [comment]
It's indeed already on my to-do list 👍

**Comment by jbelien** [comment]
Fixed!
The chart displays now the number of people per month (instead of the number per day).

![image](https://user-images.githubusercontent.com/1150563/178114112-0672bc8f-c4b9-4b29-a24a-789839f379f0.png)
