### ISSUE TITLE
unable to login -- missing login button

### ISSUE THREAD

**Issue by govvin** [osmbe/osm-welcome-belgium#637]
Here's how the landing page looks like, with the login button missing in Firefox
![image](https://user-images.githubusercontent.com/5821688/178904087-c51cb392-7c86-410a-92eb-6822822b022d.png)

If I force a page refresh, I can **very briefly** see the login button, but then it disappears. I also tried disabling the ad blockers I use (adblocker, uBlock Origin, Decentraleyes, duckduckgo privacy essentials), but that did not resolve the issue.

**Comment by jbelien** [comment]
This is strange... I use Firefox and the button displays correctly!

Can you try in another browser and in Firefox in Private life ?

**Comment by govvin** [comment]
Thanks for taking a look @jbelien . I  did try private mode, and no, it doesn't work. By the way, it's Firefox v102.0

Works in chromium, but that's really not the browser I use daily.

**Comment by jbelien** [comment]
Thanks for checking.
Unfortunately I can not replicate this issue and I'm also running Firefox 102.0.1

I don't see any reason for that button to disappear, except a local plugin (the link behind that button is `/connect/openstreetmap`, maybe you have a privacy plugin that doesn't like that).

**Comment by govvin** [comment]
Found , and removed, a recently added add-on, and everything's dandy again. :)
