### ISSUE TITLE
Tag a new mapper as “replied” before “welcomed” will cause ERROR

### ISSUE THREAD

**Issue by LaoshuBaby** [osmbe/osm-welcome-belgium#640]
Here's a example:

1. This is a user that not been welcomed:

![图片](https://user-images.githubusercontent.com/42690037/180435679-ac3296a5-63e3-4b17-b225-4f6e72a9ecbb.png)

2. I click the right button and only set this user as replied:

![图片](https://user-images.githubusercontent.com/42690037/180435449-6e4014f2-2104-4ceb-8adc-85284c37ce9b.png)

> The server returned a "500 Internal Server Error".

**Comment by jbelien** [comment]
Thanks for the notice @LaoshuBaby !
I'll have a look as soon as I have a little free time.
