### ISSUE TITLE
Many users working in Bangladesh appears like started in Colombia

### ISSUE THREAD

**Issue by angoca** [osmbe/osm-welcome-belgium#669]
I have been welcoming users from Colombia, but I have seen many of them working in Bangladesh. I am afraid if there is an area problem or similar thing:

* https://welcome.osm.be/colombia/mapper/16429918
* https://welcome.osm.be/colombia/mapper/16388127
* https://welcome.osm.be/colombia/mapper/16662644

**Comment by jbelien** [comment]
Since #808 a new mapper will appear in **every** region it is detected. This should fix the issue.
