### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by M1dgard** [osmbe/osm-welcome-belgium#7]
@gplv2 We're currently the copyright holders of the code. Do you agree to release it under the GPL? (Looking at your GitHub handle, I suspect so. 😉)

I'd propose "GPLv2 or later".

@joostschouppe You also added a line to the README. You okay with it?

**Comment by joostschouppe** [comment]
Of course

**Comment by xivk** [comment]
I would choose MIT unless you insist on the copy-left part of GPL... I wouldn't recommend it.

CC @gplv2
