### ISSUE TITLE
Add English mapathon template for DRC

### ISSUE THREAD

**Issue by clairedelune** [osmbe/osm-welcome-belgium#765]
---
name: Mapathon
title: Welcome to OpenStreetMap
---

Hi {{ mapper.displayName }}

I saw that you made your first edit on OpenStreetMap. Congratulations and thank you! You're now a member of the OpenStreetMap community.
As it seems that you joined us thanks to a mapathon likely happening outside of the area that you were mapping, feel free to check the [OSM Community Index](https://openstreetmap.community/) to connect with mappers closer to you and discover other interesting things to map.

In the Democratic Republic of the Congo, we don't only exist [online](https://openstreetmap.cd/), but we also meet sometimes [in real life](https://wiki.openstreetmap.org/wiki/Congo-Kinshasa/Calendrier).

If you've got any questions the [OpenStreetMap DRC community mailing list](https://lists.openstreetmap.org/listinfo/talk-cd) (**Please subscribe first**), is the best place to ask. As we usually exchange in French on it, feel free to use an automatic translation tool to post your message in French additionnally to English or your own language. If you think you broke something, don't know for sure how to map something, or just want to know more about OpenStreetMap, you can still get in touch with the mailing list or with the [OpenStreetMap DRC organisation](contact@openstreetmap.cd), you can also reach out via __@OSM_CD__ on Twitter or OpenStreetMap RDC on Facebook.

Here's some help to get you started:

* [Welcome Mat](https://welcome.openstreetmap.org/) gives a good overview of the What? Who? Why? How?, about and Working with OpenStreetMap 
* You can find a lot of information about how to map on [the wiki](https://wiki.openstreetmap.org/wiki/).  
* [LearnOSM](http://learnosm.org) is a good place to learn more about OSM. Instructions are available for using the iD browser editor and the more advanced JOSM editor.
* If you want to know how to tag something, the quickest solution may be to search for `site:wiki.openstreetmap.org [search term]` with your favourite search engine.
* When you save your changeset, add a clear comment on what you have changed, not just a symbol or random text ([documentation](https://wiki.openstreetmap.org/wiki/Good_changeset_comments)).
* Do not connect `landuse` to `roads`; leave a small empty area between the two.
* When using iD editor, please Zoom in enough to avoid adding duplicates.
* Kindly avoid using UPPERCASE for names e.g. `TIPTOE LANE`, use `Tiptoe Lane` instead
* There's also a [global weekly newsletter about the OpenStreetMap world](https://weeklyosm.eu/) you can subscribe to.

Happy Mapping!

**Comment by jbelien** [comment]
Thanks you @clairedelune !
The new template has been added to https://welcome.osm.be/ ✅
