### ISSUE TITLE
Re-create an osmcha.id for France

### ISSUE THREAD

**Issue by llongour** [osmbe/osm-welcome-belgium#772]
I don't know why but one of my commits from the previous PR #768  had no effect. The `osmcha.id` hasn't changed

https://github.com/osmbe/osm-welcome-tool/pull/768/commits/b8c210e4ed43167450c937dac292a53c98ef58be

Thanks again

**Comment by jbelien** [comment]
I indeed reverted it, it wasn't necessary to change it.
