### ISSUE TITLE
HTTP 500 when trying to log in

### ISSUE THREAD

**Issue by RicoElectrico** [osmbe/osm-welcome-belgium#773]
I get such an error message. Revoked OAuth2 access as well, did not help.

```
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/app/vendor/doctrine/dbal/src/Driver/PDO/Statement.php on line 134
Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

**Comment by jbelien** [comment]
Sorry about this @RicoElectrico !

It's related to the migration done to Digital Ocean AppPlatform.
We indeed noticed that performances are REALLY bad and I'm investigation another solution (see https://github.com/osmbe/community_planning/issues/41).

**Comment by jbelien** [comment]
I've reverted to the previous setup.
Unfortunately I couldn't recuperate the work done since the migration. My apologies for this.
