### ISSUE TITLE
List of placeholder for templates

### ISSUE THREAD

**Issue by angoca** [osmbe/osm-welcome-belgium#782]
I would like to know the placeholder one can use in the templates. I only know this "mapper.displayName", but it seems there are more, but I have not found them in the documentation (Contributing.md).

**Comment by jbelien** [comment]
Good point! 👍 
I'll add it to the documentation.

**Comment by jbelien** [comment]
See https://github.com/osmbe/osm-welcome-tool/blob/2.x/CONTRIBUTING.md#what-variablesplaceholders-can-you-use-in-your-template-
