### ISSUE TITLE
Include Telegram channel in page and/or Github

### ISSUE THREAD

**Issue by angoca** [osmbe/osm-welcome-belgium#793]
I belong to the Telegram channel, which is an excellent way to help new people.

It will be interesting to include the channel on the main page and this GitHub repository.

**Comment by jbelien** [comment]
Hello @angoca ,

Not sure I understand your request.
But feel free to add a link to Telegram in the template messages sent to the new users in the region you're contributing.

**Comment by angoca** [comment]
No, I mean somewhere in https://welcome.osm.be/.

In fact, I have just discovered the Telegram group is a private one; therefore, it does not have a public URL. 

I think an open Telegram group could be a way to help people to define new areas, improve translations, and get involved in platform maintenance. This way, more people could start using the platform.

**Comment by jbelien** [comment]
Oh okay, you're talking about the "LCCWG - welcome tool group" Telegram group, right ?

That group wasn't really meant to be shared publicly but was setup in the early days of the new version of the Welcome Tool so I could share the progress of the development of the new version with people of LCCWG.
