### ISSUE TITLE
Request for adding Korean

### ISSUE THREAD

**Issue by depth221** [osmbe/osm-welcome-belgium#835]
Hi,
I recently added a welcome message for mappers for South Korea. (#814)
So could you add Korean to the Crowdin? Thanks in advance.

**Comment by jbelien** [comment]
Done! Thanks a lot already!

**Comment by jbelien** [comment]
Thanks a lot @depth221 ! 👍 
That has been merged in bfb5d7abf2567705278f34b773d4d4a6b795feec

**Comment by jbelien** [comment]
🚀 And deployed: https://welcome.osm.be/?l=ko
