### ISSUE TITLE
Something wrong with the geographical determination ?

### ISSUE THREAD

**Issue by Jakkajakka** [osmbe/osm-welcome-belgium#882]
There are occasional reports in "https://welcome.osm.be/belgium/list" of new users not editing in Belgium. Is there something wrong with the geographical determination ?

**Comment by jbelien** [comment]
Hello @Jakkajakka,

Nothing wrong with the detection.
But some user have huge changeset that covers multiple countries and I'm guessing that's what you're referring to.

A few weeks ago, I've grayed out in the mappers list those huge changeset (that covers more than 3 countries), you can skip those mappers.

![image](https://user-images.githubusercontent.com/1150563/210563192-ca61357d-bf11-4668-82f8-68303818a625.png)
