### ISSUE TITLE
Many regions covered by changes covering large areas

### ISSUE THREAD

**Issue by angoca** [osmbe/osm-welcome-belgium#884]
Hi,

I see the user [The Thirsty Traveler](https://www.openstreetmap.org/user/The%20Thirsty%20Traveler) has modified 2 nodes, one in New York and one in Sydney: https://www.openstreetmap.org/changeset/130703748. This "creates" a very large area covering half of the world and appearing in all regions in Welcome Tool. 

I see it in Bogota, and thanks to his answer, I identify this issue in the tool.

What is the meaning of the users in grey in the list?

**Comment by jbelien** [comment]
> What is the meaning of the users in grey in the list?

Users grayed out can be ignore.
They are grayed out if they're detected in more than 3 regions ; meaning it's most probably a changeset that is way too big and covers an area too big.

**Comment by angoca** [comment]
Thank you for the explanation. I was not aware of this great feature.

Can we not include regions where this user didn't do anything? I suggest not using a rectangle between the modifications. In this case, Colombia is in the square created between New York and Sydney, as well as many other areas, but that creates confusion because it will be necessary to validate all changes to validate whether the welcoming area was touched.

**Comment by angoca** [comment]
Please take a look at this user: https://welcome.osm.be/south-america/bogota/mapper/10292845

@mfrasca removed "the mapper has been welcomed." but I am using the "Not welcomed yet" list to send a message to new users. If the button is moved back once someone has sent a message, one could send them a welcome message twice.
However, what Mario is saying is true; this user does not need to be welcomed by the Panama community.

Probably, we need some new features for grey users to prevent this button war:

* A validation per region (Brazil and/or Mexico, excluding Panama and Colombia).
* Another state for that button.

**Comment by jbelien** [comment]
> Can we not include regions where this user didn't do anything? I suggest not using a rectangle between the modifications. In this case, Colombia is in the square created between New York and Sydney, as well as many other areas, but that creates confusion because it will be necessary to validate all changes to validate whether the welcoming area was touched.

I fully agree with you but that's OSMCha features, not the Welcome Tool : I fully rely on the detection made by OSMCha.

**Comment by mfrasca** [comment]
> @mfrasca removed "the mapper has been welcomed."

sure, because the mapper had not been welcomed, and @angoca was using that flag for a different purpose.

some time ago I opened #494, related to this one.

lacking implementation of #494, I've been adding a note to "not welcomed" users, signifying someone had a look at the user, decided not to welcome, and commented about it.

**Comment by mfrasca** [comment]
> Users grayed out can be ignore.

that's **possibly** ignored, because the set of changes does include at least two places, however far from each other.

:wink:
