### ISSUE TITLE
Cannot sync my repo with yours

### ISSUE THREAD

**Issue by angoca** [osmbe/osm-welcome-belgium#885]
I am hitting this issue:

https://github.com/MaptimeBogota/osm-welcome-tool/actions/runs/3876419478/jobs/6610344368

when creating a pull request to mine: https://github.com/MaptimeBogota/osm-welcome-tool/pull/4

**Comment by jbelien** [comment]
As you can see on the main branch `2.x` here, I have the same issue. 😄 
I'll investigate ; it probably just needs a `composer update` instead of `composer install`.

**Comment by jbelien** [comment]
I've upgraded the package that was causing issue with PHP 8.2.

You should now be able to use PHP 8.2.
