### ISSUE TITLE
Request for adding Ukrainian

### ISSUE THREAD

**Issue by Andygol** [osmbe/osm-welcome-belgium#896]
It would be great to have 🇺🇦 Ukrainian on https://crowdin.com/project/osm-welcome-tool 🙏

**Comment by jbelien** [comment]
Done!
You can now translate the tool to Ukrainian!
Thanks a lot. 🎉

**Comment by jbelien** [comment]
Ping me when translation is ready to be deployed.

**Comment by Andygol** [comment]
Yeap, sure.

Thank you for cooperation.

**Comment by Andygol** [comment]
@jbelien Ukrainian 💯 ready - https://crowdin.com/project/osm-welcome-tool/uk

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/?l=uk
