### ISSUE TITLE
Request to add Portuguese (Portugal) language

### ISSUE THREAD

**Issue by AntMadeira** [osmbe/osm-welcome-belgium#898]
Hi there.
I'm requesting to add Portuguese (Portugal) language at Crowdin.

Regards.

**Comment by jbelien** [comment]
Done!
Thanks a lot for your contribution.
Ping me when translation is ready and I'll deploy it. 🎉

**Comment by AntMadeira** [comment]
Thanks, @jbelien!
I just finished translating all strings at Crowdin.

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/?l=pt_PT

Thanks a lot for your contribution!
