### ISSUE TITLE
Don't know how to contribute

### ISSUE THREAD

**Issue by AntMadeira** [osmbe/osm-welcome-belgium#924]
Hi there.

I tried to follow the Contribute suggestions to add Portugal to osm-welcome-tool, but when I try to edit the files, I get the message:

> You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork AntMadeira/osm-welcome-tool, so you can send a pull request. 

I edited the regions.yaml file but it seems the edition went to another repository.
I also created a new file with Portugal geoson, but it happened the same.

Can anyone help this newbie?

**Comment by jbelien** [comment]
No worries!
You should be able to open a new Pull Request in this repository from your forked repository.

But if you don't succeed, no problem, just point me to the files in your repository and I'll come pick it up. 🙂

**Comment by AntMadeira** [comment]
Ok, let's try:
https://github.com/AntMadeira/osm-welcome-tool/blob/2.x/config/regions.yaml
https://github.com/AntMadeira/osm-welcome-tool/blob/2.x/assets/regions/portugal.geoson

I hope this is it... :/

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/europe/portugal/list

**Comment by AntMadeira** [comment]
Thank you very much!
