### ISSUE TITLE
Add PT-BR language on Crowdin

### ISSUE THREAD

**Issue by matheusgomesms** [osmbe/osm-welcome-belgium#942]
Hey guys,

Following the great work at #898, could you please add PT-BR to be translated? I will then add the translation there, once it is allowed. Thanks!

**Comment by jbelien** [comment]
Awesome!
I've added it to Crowding.
Ping me when the translation is ready and I'll merge it.

**Comment by matheusgomesms** [comment]
Thanks, 100% translated. So easy, given @AntMadeira had all the hard work for PT-PT.

**Comment by jbelien** [comment]
🚀 Deployed: https://welcome.osm.be/?l=pt_BR
